#!/usr/bin/env bash

headers() {
  printenv | sort | grep 'HTTP_\|REQUEST_\|QUERY' | tee /dev/fd/2
}

process() {
  ! [[ "$QUERY_STRING" ]] && return

  env ${QUERY_STRING//&/ } bash -c 'httpd -d  $body' | tee -a /tmp/messages
  echo '' >> /tmp/messages
}

cat << EOF
Content-type: text/html

<p><em>Hello World!</em></p>

<pre>
body: $(process)

date: $(date)
hostname: ${HOSTNAME}
</pre>

<hr/>
Previous messages:
<pre>
$(tac /tmp/messages)
</pre
<hr/>
<a href="/">home</a>
EOF